"""empty message

Revision ID: 27b85b3fb9b
Revises: 497d6c2194a
Create Date: 2015-10-10 20:34:17.632229

"""

# revision identifiers, used by Alembic.
revision = '27b85b3fb9b'
down_revision = '497d6c2194a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    ### end Alembic commands ###
