"""empty message

Revision ID: 46e2e82b373
Revises: 59cd47c905a
Create Date: 2015-10-10 16:21:15.167968

"""

# revision identifiers, used by Alembic.
revision = '46e2e82b373'
down_revision = '59cd47c905a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('relationship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relationship_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_constraint('users_house_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'house_id')
    op.drop_table('house')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('house_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_house_id_fkey', 'users', 'house', ['house_id'], ['id'], ondelete='SET NULL')
    op.create_table('house',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], name='house_owner_fkey'),
    sa.PrimaryKeyConstraint('id', name='house_pkey')
    )
    op.drop_table('relationships')
    ### end Alembic commands ###
