"""empty message

Revision ID: 59cd47c905a
Revises: None
Create Date: 2015-10-10 15:06:31.658499

"""

# revision identifiers, used by Alembic.
revision = '59cd47c905a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_house_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'house', ['house_id'], ['id'], ondelete='SET NULL')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_house_id_fkey', 'users', 'house', ['house_id'], ['id'])
    ### end Alembic commands ###
